// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://theobmfkdlsfsyogpcxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRoZW9ibWZrZGxzZnN5b2dwY3h3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNDE1OTcsImV4cCI6MjA1ODkxNzU5N30.5jx1t64A4OnFnGWopE8osl2uoMe9iWiZLkXiM4vK_XA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);